
(load "define.scm")
(define (add-components) (begin
(append-component-with-attribs "ampermeter.sym" '(43700 . 41000)  "A")
(append-component-with-attribs "brake.sym" '(43300 . 41900)  "B")
(append-component-with-attribs "cabinet.sym" '(42700 . 42700)  "Cab")
(append-component-with-attribs "motor-ac.sym" '(41900 . 43300)  "EMS")
(append-component-with-attribs "fuse.sym" '(41000 . 43700)  "F1")
(append-component-with-attribs "fuse.sym" '(40000 . 43800)  "F2")
(append-component-with-attribs "generator.sym" '(39000 . 43700)  "G")
(append-component-with-attribs "inverter.sym" '(38100 . 43300)  "I")
(append-component-with-attribs "omron-relay.sym" '(37300 . 42700)  "K1")
(append-component-with-attribs "omron-relay.sym" '(36700 . 41900)  "K2")
(append-component-with-attribs "omron-relay.sym" '(36300 . 41000)  "K3")
(append-component-with-attribs "omron-relay.sym" '(36200 . 40000)  "K4")
(append-component-with-attribs "omron-relay.sym" '(36300 . 39000)  "K5")
(append-component-with-attribs "omron-relay.sym" '(36700 . 38100)  "K6")
(append-component-with-attribs "fotek-relay.sym" '(37300 . 37300)  "KFotek1")
(append-component-with-attribs "fotek-relay.sym" '(38100 . 36700)  "KFotek2")
(append-component-with-attribs "lamp.sym" '(39000 . 36300)  "L")
(append-component-with-attribs "motor-ac.sym" '(40000 . 36200)  "M")
(append-component-with-attribs "motor-ac.sym" '(41000 . 36300)  "RPM")
(append-component-with-attribs "motor-ac.sym" '(41900 . 36700)  "SMain")
(append-component-with-attribs "ampermeter.sym" '(42700 . 37300)  "SpAdj")
(append-component-with-attribs "switch-spst-no.sym" '(43300 . 38100)  "Sw")
(append-component-with-attribs "ampermeter.sym" '(43700 . 39000)  "TAdj")
(append-component-with-attribs "main-terminal.sym" '(43800 . 40000)  "X")
))
(define (add-nets) (begin
(append-net '("X" . "1") '("Sw" . "2"))
(append-net '("Sw" . "2") '("L" . "1"))
(append-net '("L" . "1") '("KFotek1" . "6"))
(append-net '("KFotek1" . "6") '("KFotek1" . "7"))
(append-net '("KFotek1" . "7") '("K6" . "12"))
(append-net '("K6" . "12") '("K1" . "5"))
(append-net '("K1" . "5") '("G" . "1"))
(append-net '("G" . "1") '("EMS" . "1"))
(append-net '("K3" . "9") '("K2" . "1"))
(append-net '("K6" . "14") '("K3" . "5"))
(append-net '("K3" . "5") '("K2" . "12"))
(append-net '("X" . "16") '("K3" . "14"))
(append-net '("K3" . "14") '("G" . "16"))
(append-net '("X" . "18") '("KFotek1" . "4"))
(append-net '("KFotek1" . "4") '("K4" . "12"))
(append-net '("K4" . "12") '("G" . "18"))
(append-net '("X" . "19") '("K4" . "8"))
(append-net '("K4" . "8") '("K4" . "14"))
(append-net '("K4" . "14") '("G" . "19"))
(append-net '("X" . "2") '("L" . "2"))
(append-net '("L" . "2") '("KFotek2" . "8"))
(append-net '("KFotek2" . "8") '("KFotek1" . "8"))
(append-net '("KFotek1" . "8") '("K6" . "13"))
(append-net '("K6" . "13") '("K5" . "13"))
(append-net '("K5" . "13") '("K4" . "13"))
(append-net '("K4" . "13") '("K3" . "13"))
(append-net '("K3" . "13") '("K2" . "13"))
(append-net '("K2" . "13") '("K1" . "13"))
(append-net '("K1" . "13") '("B" . "2"))
(append-net '("X" . "21") '("K6" . "8"))
(append-net '("K6" . "8") '("B" . "21"))
(append-net '("KFotek2" . "2") '("K5" . "14"))
(append-net '("Sw" . "1") '("K1" . "14"))
(append-net '("X" . "6") '("K2" . "9"))
(append-net '("K2" . "9") '("K1" . "9"))
(append-net '("K1" . "9") '("Cab" . "6-1"))
(append-net '("X" . "7") '("K4" . "9"))
(append-net '("K4" . "9") '("K2" . "5"))
(append-net '("K2" . "5") '("Cab" . "7-1"))
(append-net '("KFotek1" . "5") '("K4" . "1"))
(append-net '("K4" . "1") '("K2" . "14"))
(append-net '("KFotek2" . "5") '("KFotek2" . "6"))
(append-net '("KFotek2" . "6") '("KFotek1" . "1"))
(append-net '("K6" . "9") '("I" . "12"))
(append-net '("X" . "COM") '("K5" . "9"))
(append-net '("K5" . "9") '("G" . "COM"))
(append-net '("TAdj" . "2") '("I" . "5"))
(append-net '("K6" . "5") '("I" . "11"))
(append-net '("RPM" . "M+") '("I" . "7"))
(append-net '("X" . "N") '("SMain" . "N"))
(append-net '("SMain" . "N") '("SMain" . "N"))
(append-net '("SMain" . "N") '("F2" . "1"))
(append-net '("X" . "NO") '("K5" . "5"))
(append-net '("K5" . "5") '("G" . "NO"))
(append-net '("X" . "PE") '("X" . "PE"))
(append-net '("X" . "PE") '("M" . "PE"))
(append-net '("X" . "R") '("SMain" . "R"))
(append-net '("F2" . "2") '("F1" . "2"))
(append-net '("F1" . "2") '("EMS" . "2"))
(append-net '("SMain" . "R1") '("I" . "R1"))
(append-net '("I" . "R1") '("F1" . "1"))
(append-net '("X" . "S") '("SMain" . "S"))
(append-net '("TAdj" . "3") '("SpAdj" . "3"))
(append-net '("SpAdj" . "3") '("SMain" . "S1"))
(append-net '("SMain" . "S1") '("RPM" . "S1"))
(append-net '("RPM" . "S1") '("I" . "3"))
(append-net '("I" . "3") '("I" . "8"))
(append-net '("I" . "8") '("I" . "S1"))
(append-net '("SpAdj" . "2") '("I" . "2"))
(append-net '("TAdj" . "1") '("SpAdj" . "1"))
(append-net '("SpAdj" . "1") '("I" . "4"))
(append-net '("X" . "T") '("SMain" . "T"))
(append-net '("SMain" . "T1") '("I" . "T1"))
(append-net '("X" . "U") '("M" . "U"))
(append-net '("M" . "U") '("I" . "U"))
(append-net '("X" . "V") '("M" . "V"))
(append-net '("M" . "V") '("I" . "V"))
(append-net '("I" . "V") '("A" . "1"))
(append-net '("A" . "1") '("A" . "2"))
(append-net '("X" . "W") '("M" . "W"))
(append-net '("M" . "W") '("I" . "W"))
(append-net '("KFotek2" . "1") '("KFotek2" . "3"))
(append-net '("KFotek2" . "3") '("KFotek2" . "4"))
(append-net '("KFotek2" . "4") '("KFotek2" . "7"))
(append-net '("KFotek2" . "7") '("KFotek1" . "2"))
(append-net '("KFotek1" . "2") '("KFotek1" . "3"))
(append-net '("KFotek1" . "3") '("K6" . "1"))
(append-net '("K6" . "1") '("K6" . "4"))
(append-net '("K6" . "4") '("K5" . "1"))
(append-net '("K5" . "1") '("K5" . "4"))
(append-net '("K5" . "4") '("K5" . "8"))
(append-net '("K5" . "8") '("K5" . "12"))
(append-net '("K5" . "12") '("K4" . "5"))
(append-net '("K4" . "5") '("K4" . "4"))
(append-net '("K4" . "4") '("K3" . "1"))
(append-net '("K3" . "1") '("K3" . "4"))
(append-net '("K3" . "4") '("K3" . "8"))
(append-net '("K3" . "8") '("K3" . "12"))
(append-net '("K3" . "12") '("K2" . "4"))
(append-net '("K2" . "4") '("K2" . "8"))
(append-net '("K2" . "8") '("K1" . "1"))
(append-net '("K1" . "1") '("K1" . "4"))
(append-net '("K1" . "4") '("K1" . "8"))
(append-net '("K1" . "8") '("K1" . "12"))
(append-net '("K1" . "12") '("I" . "1"))
(append-net '("I" . "1") '("I" . "6"))
(append-net '("I" . "6") '("I" . "10"))
(append-net '("I" . "9") '("I" . "15"))
(append-net '("I" . "13") '("I" . "14"))
))
